// 需要验证的token路径
export const tokenUrls = [
    "/addMessage",
    "/getPerson",
    "/toggleStatus",
    "/removeData",
    "/addReply",
    "/toggleReply",
    "/removeReply",
    "/addPhoto",
    "/togglePhoto",
    "/removePhoto",
    "/toggleUser",
    "//addArticleType",
    "/toggleArticleType",
    "/removeArticleType",
    "/addArticle",
    "/toggleArticle",
    "/removeArticle",
    "/eidtArticle",
]